{% set name = "cmaps" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://files.pythonhosted.org/packages/57/a8/a7c56fe258e1e6b868e246c6c981ef32e253987dd1f9544f5dc9fa882689/cmaps-2.0.0.tar.gz"
  sha256: "4842859d80084837ce65542001e029e55eeb5a69d6003921ee68561d0da74bb5"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=2.2
    - packaging
    - numpy
    - python >=3.6

test:
  imports:
    - cmaps

about:
  home: https://github.com/hhuangwx/cmaps
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: user defined colormaps in matplotlib
  dev_url: https://github.com/hhuangwx/cmaps

extra:
  recipe-maintainers:
    - hhuangwx
