{% set name = "cmaps" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://files.pythonhosted.org/packages/2f/c8/15cb109031c1520caa02730eae83f760e15ed39aad1bc7932e6b6a42cf5d/cmaps-2.0.1.tar.gz"
  sha256: "6344fe9874281ce869af63c318c07632e73021019334d204617fcd3f28d55fa7"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=2.2
    - packaging
    - numpy
    - python >=3.6

test:
  imports:
    - cmaps

about:
  home: https://github.com/hhuangwx/cmaps
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: user defined colormaps in matplotlib
  dev_url: https://github.com/hhuangwx/cmaps

extra:
  recipe-maintainers:
    - hhuangwx
